
package com.mes.ps.billing.dto.profitstars.report;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionReportingSoap", targetNamespace = "https://ssl.selectpayment.com/PV")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionReportingSoap {


    /**
     * 
     * @param wspaymentType
     * @param beginTransDate
     * @param wsauthResponseCode
     * @param wsopType
     * @param storeKey
     * @param wstransStatus
     * @param fromAmount
     * @param locationIds
     * @param toAmount
     * @param wsdisplayFields
     * @param entityId
     * @param wspaymentOrigin
     * @param storeId
     * @param endTransDate
     * @param wsdateType
     * @param wssettlementStatus
     * @param wssettlementType
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "TransactionReport", action = "https://ssl.selectpayment.com/PV/TransactionReport")
    @WebResult(name = "TransactionReportResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "TransactionReport", targetNamespace = "https://ssl.selectpayment.com/PV", className = "TransactionReport")
    @ResponseWrapper(localName = "TransactionReportResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "TransactionReportResponse")
    public Object transactionReport(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "wsdisplayFields", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSDisplayFields wsdisplayFields,
        @WebParam(name = "locationIds", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfInt locationIds,
        @WebParam(name = "wstransStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSTransactionStatus wstransStatus,
        @WebParam(name = "wssettlementType", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementType wssettlementType,
        @WebParam(name = "wspaymentType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSPaymentType wspaymentType,
        @WebParam(name = "wspaymentOrigin", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSPaymentOrigin wspaymentOrigin,
        @WebParam(name = "wssettlementStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementStatus wssettlementStatus,
        @WebParam(name = "wsauthResponseCode", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSAuthResponseCode wsauthResponseCode,
        @WebParam(name = "wsopType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSOperationType wsopType,
        @WebParam(name = "beginTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar beginTransDate,
        @WebParam(name = "endTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar endTransDate,
        @WebParam(name = "wsdateType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSReportDateType wsdateType,
        @WebParam(name = "fromAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String fromAmount,
        @WebParam(name = "toAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String toAmount);

    /**
     * 
     * @param wspaymentType
     * @param beginTransDate
     * @param wsauthResponseCode
     * @param wsopType
     * @param storeKey
     * @param wstransStatus
     * @param fromAmount
     * @param locationIds
     * @param toAmount
     * @param wsdisplayFields
     * @param entityId
     * @param wspaymentOrigin
     * @param storeId
     * @param endTransDate
     * @param wsdateType
     * @param wssettlementStatus
     * @param wssettlementType
     * @return
     *     returns ArrayOfWSTransactionReport
     */
    @WebMethod(operationName = "GetTransactionReport", action = "https://ssl.selectpayment.com/PV/GetTransactionReport")
    @WebResult(name = "GetTransactionReportResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "GetTransactionReport", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetTransactionReport")
    @ResponseWrapper(localName = "GetTransactionReportResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetTransactionReportResponse")
    public ArrayOfWSTransactionReport getTransactionReport(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "wsdisplayFields", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSDisplayFields wsdisplayFields,
        @WebParam(name = "locationIds", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfInt locationIds,
        @WebParam(name = "wstransStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSTransactionStatus wstransStatus,
        @WebParam(name = "wssettlementType", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementType wssettlementType,
        @WebParam(name = "wspaymentType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSPaymentType wspaymentType,
        @WebParam(name = "wspaymentOrigin", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSPaymentOrigin wspaymentOrigin,
        @WebParam(name = "wssettlementStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementStatus wssettlementStatus,
        @WebParam(name = "wsauthResponseCode", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSAuthResponseCode wsauthResponseCode,
        @WebParam(name = "wsopType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSOperationType wsopType,
        @WebParam(name = "beginTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar beginTransDate,
        @WebParam(name = "endTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar endTransDate,
        @WebParam(name = "wsdateType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSReportDateType wsdateType,
        @WebParam(name = "fromAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String fromAmount,
        @WebParam(name = "toAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String toAmount);

    /**
     * 
     * @param wspaymentType
     * @param beginTransDate
     * @param wsauthResponseCode
     * @param wsopType
     * @param storeKey
     * @param wstransStatus
     * @param fromAmount
     * @param locationIds
     * @param toAmount
     * @param wsdisplayFields
     * @param entityId
     * @param wspaymentOrigin
     * @param storeId
     * @param endTransDate
     * @param wssettlementStatus
     * @param wssettlementType
     * @param wstransEvent
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "HistoricalEventReport", action = "https://ssl.selectpayment.com/PV/HistoricalEventReport")
    @WebResult(name = "HistoricalEventReportResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "HistoricalEventReport", targetNamespace = "https://ssl.selectpayment.com/PV", className = "HistoricalEventReport")
    @ResponseWrapper(localName = "HistoricalEventReportResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "HistoricalEventReportResponse")
    public Object historicalEventReport(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "wsdisplayFields", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSDisplayFields wsdisplayFields,
        @WebParam(name = "locationIds", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfInt locationIds,
        @WebParam(name = "wstransEvent", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSTransactionEvent wstransEvent,
        @WebParam(name = "wstransStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSTransactionStatus wstransStatus,
        @WebParam(name = "wssettlementType", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementType wssettlementType,
        @WebParam(name = "wspaymentType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSPaymentType wspaymentType,
        @WebParam(name = "wspaymentOrigin", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSPaymentOrigin wspaymentOrigin,
        @WebParam(name = "wssettlementStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementStatus wssettlementStatus,
        @WebParam(name = "wsauthResponseCode", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSAuthResponseCode wsauthResponseCode,
        @WebParam(name = "wsopType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSOperationType wsopType,
        @WebParam(name = "beginTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar beginTransDate,
        @WebParam(name = "endTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar endTransDate,
        @WebParam(name = "fromAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String fromAmount,
        @WebParam(name = "toAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String toAmount);

    /**
     * 
     * @param wspaymentType
     * @param beginTransDate
     * @param wsauthResponseCode
     * @param wsopType
     * @param storeKey
     * @param wstransStatus
     * @param fromAmount
     * @param locationIds
     * @param toAmount
     * @param wsdisplayFields
     * @param entityId
     * @param wspaymentOrigin
     * @param storeId
     * @param endTransDate
     * @param wssettlementStatus
     * @param wssettlementType
     * @param wstransEvent
     * @return
     *     returns ArrayOfWSEventReport
     */
    @WebMethod(operationName = "GetHistoricalEventReport", action = "https://ssl.selectpayment.com/PV/GetHistoricalEventReport")
    @WebResult(name = "GetHistoricalEventReportResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "GetHistoricalEventReport", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetHistoricalEventReport")
    @ResponseWrapper(localName = "GetHistoricalEventReportResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetHistoricalEventReportResponse")
    public ArrayOfWSEventReport getHistoricalEventReport(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "wsdisplayFields", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSDisplayFields wsdisplayFields,
        @WebParam(name = "locationIds", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfInt locationIds,
        @WebParam(name = "wstransEvent", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSTransactionEvent wstransEvent,
        @WebParam(name = "wstransStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSTransactionStatus wstransStatus,
        @WebParam(name = "wssettlementType", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementType wssettlementType,
        @WebParam(name = "wspaymentType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSPaymentType wspaymentType,
        @WebParam(name = "wspaymentOrigin", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSPaymentOrigin wspaymentOrigin,
        @WebParam(name = "wssettlementStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementStatus wssettlementStatus,
        @WebParam(name = "wsauthResponseCode", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSAuthResponseCode wsauthResponseCode,
        @WebParam(name = "wsopType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSOperationType wsopType,
        @WebParam(name = "beginTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar beginTransDate,
        @WebParam(name = "endTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar endTransDate,
        @WebParam(name = "fromAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String fromAmount,
        @WebParam(name = "toAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String toAmount);

    /**
     * 
     * @param wspaymentType
     * @param beginTransDate
     * @param wsauthResponseCode
     * @param wsopType
     * @param storeKey
     * @param wstransStatus
     * @param fromAmount
     * @param locationIds
     * @param toAmount
     * @param wsdisplayFields
     * @param entityId
     * @param wspaymentOrigin
     * @param storeId
     * @param endTransDate
     * @param wssettlementStatus
     * @param wssettlementType
     * @param wsfaceFeeType
     * @param wstransEvent
     * @return
     *     returns ArrayOfWSEventWithTransactionDetailReport
     */
    @WebMethod(operationName = "GetHistoricalEventWithTransactionDetailReport", action = "https://ssl.selectpayment.com/PV/GetHistoricalEventWithTransactionDetailReport")
    @WebResult(name = "GetHistoricalEventWithTransactionDetailReportResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "GetHistoricalEventWithTransactionDetailReport", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetHistoricalEventWithTransactionDetailReport")
    @ResponseWrapper(localName = "GetHistoricalEventWithTransactionDetailReportResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetHistoricalEventWithTransactionDetailReportResponse")
    public ArrayOfWSEventWithTransactionDetailReport getHistoricalEventWithTransactionDetailReport(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "wsdisplayFields", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSDisplayFields wsdisplayFields,
        @WebParam(name = "locationIds", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfInt locationIds,
        @WebParam(name = "wstransEvent", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSTransactionEvent wstransEvent,
        @WebParam(name = "wstransStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSTransactionStatus wstransStatus,
        @WebParam(name = "wssettlementType", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementType wssettlementType,
        @WebParam(name = "wspaymentType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSPaymentType wspaymentType,
        @WebParam(name = "wspaymentOrigin", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSPaymentOrigin wspaymentOrigin,
        @WebParam(name = "wssettlementStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementStatus wssettlementStatus,
        @WebParam(name = "wsauthResponseCode", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSAuthResponseCode wsauthResponseCode,
        @WebParam(name = "wsopType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSOperationType wsopType,
        @WebParam(name = "wsfaceFeeType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSFaceFeeType wsfaceFeeType,
        @WebParam(name = "beginTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar beginTransDate,
        @WebParam(name = "endTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar endTransDate,
        @WebParam(name = "fromAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String fromAmount,
        @WebParam(name = "toAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String toAmount);

    /**
     * 
     * @param wspaymentType
     * @param beginTransDate
     * @param wsauthResponseCode
     * @param wsopType
     * @param storeKey
     * @param wstransStatus
     * @param fromAmount
     * @param locationIds
     * @param toAmount
     * @param wsdisplayFields
     * @param entityId
     * @param wspaymentOrigin
     * @param storeId
     * @param wstransEvents
     * @param endTransDate
     * @param wssettlementStatus
     * @param wssettlementType
     * @return
     *     returns ArrayOfWSEventReport
     */
    @WebMethod(operationName = "GetHistoricalEvents", action = "https://ssl.selectpayment.com/PV/GetHistoricalEvents")
    @WebResult(name = "GetHistoricalEventsResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "GetHistoricalEvents", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetHistoricalEvents")
    @ResponseWrapper(localName = "GetHistoricalEventsResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetHistoricalEventsResponse")
    public ArrayOfWSEventReport getHistoricalEvents(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "wsdisplayFields", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSDisplayFields wsdisplayFields,
        @WebParam(name = "locationIds", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfInt locationIds,
        @WebParam(name = "wstransEvents", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSTransactionEvent wstransEvents,
        @WebParam(name = "wstransStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSTransactionStatus wstransStatus,
        @WebParam(name = "wssettlementType", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementType wssettlementType,
        @WebParam(name = "wspaymentType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSPaymentType wspaymentType,
        @WebParam(name = "wspaymentOrigin", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSPaymentOrigin wspaymentOrigin,
        @WebParam(name = "wssettlementStatus", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfWSSettlementStatus wssettlementStatus,
        @WebParam(name = "wsauthResponseCode", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSAuthResponseCode wsauthResponseCode,
        @WebParam(name = "wsopType", targetNamespace = "https://ssl.selectpayment.com/PV")
        WSOperationType wsopType,
        @WebParam(name = "beginTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar beginTransDate,
        @WebParam(name = "endTransDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar endTransDate,
        @WebParam(name = "fromAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String fromAmount,
        @WebParam(name = "toAmount", targetNamespace = "https://ssl.selectpayment.com/PV")
        String toAmount);

    /**
     * 
     * @param beginDate
     * @param endDate
     * @param storeKey
     * @param locationIds
     * @param entityId
     * @param storeId
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "CreditandDebitReports", action = "https://ssl.selectpayment.com/PV/CreditandDebitReports")
    @WebResult(name = "CreditandDebitReportsResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "CreditandDebitReports", targetNamespace = "https://ssl.selectpayment.com/PV", className = "CreditandDebitReports")
    @ResponseWrapper(localName = "CreditandDebitReportsResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "CreditandDebitReportsResponse")
    public Object creditandDebitReports(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "locationIds", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfInt locationIds,
        @WebParam(name = "beginDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar beginDate,
        @WebParam(name = "endDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param beginDate
     * @param endDate
     * @param storeKey
     * @param locationIds
     * @param entityId
     * @param storeId
     * @return
     *     returns ArrayOfWSCreditDebitReport
     */
    @WebMethod(operationName = "GetCreditandDebitReports", action = "https://ssl.selectpayment.com/PV/GetCreditandDebitReports")
    @WebResult(name = "GetCreditandDebitReportsResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "GetCreditandDebitReports", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetCreditandDebitReports")
    @ResponseWrapper(localName = "GetCreditandDebitReportsResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetCreditandDebitReportsResponse")
    public ArrayOfWSCreditDebitReport getCreditandDebitReports(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "locationIds", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfInt locationIds,
        @WebParam(name = "beginDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar beginDate,
        @WebParam(name = "endDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param storeKey
     * @param entityId
     * @param storeId
     * @param batchId
     * @return
     *     returns ArrayOfWSSettlementBatch
     */
    @WebMethod(operationName = "CreditsandDebitsTransactionDetailReport", action = "https://ssl.selectpayment.com/PV/CreditsandDebitsTransactionDetailReport")
    @WebResult(name = "CreditsandDebitsTransactionDetailReportResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "CreditsandDebitsTransactionDetailReport", targetNamespace = "https://ssl.selectpayment.com/PV", className = "CreditsandDebitsTransactionDetailReport")
    @ResponseWrapper(localName = "CreditsandDebitsTransactionDetailReportResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "CreditsandDebitsTransactionDetailReportResponse")
    public ArrayOfWSSettlementBatch creditsandDebitsTransactionDetailReport(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "batchId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long batchId);

    /**
     * 
     * @param storeKey
     * @param entityId
     * @param storeId
     * @return
     *     returns ArrayOfWSCollectionSetting
     */
    @WebMethod(operationName = "GetCollectionSettings", action = "https://ssl.selectpayment.com/PV/GetCollectionSettings")
    @WebResult(name = "GetCollectionSettingsResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "GetCollectionSettings", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetCollectionSettings")
    @ResponseWrapper(localName = "GetCollectionSettingsResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetCollectionSettingsResponse")
    public ArrayOfWSCollectionSetting getCollectionSettings(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId);

    /**
     * 
     * @param returnedBeginDate
     * @param storeKey
     * @param locationIds
     * @param entityId
     * @param storeId
     * @param returnedEndDate
     * @return
     *     returns ArrayOfWSCollection
     */
    @WebMethod(operationName = "GetCollectionReportBuilder", action = "https://ssl.selectpayment.com/PV/GetCollectionReportBuilder")
    @WebResult(name = "GetCollectionReportBuilderResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "GetCollectionReportBuilder", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetCollectionReportBuilder")
    @ResponseWrapper(localName = "GetCollectionReportBuilderResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetCollectionReportBuilderResponse")
    public ArrayOfWSCollection getCollectionReportBuilder(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "locationIds", targetNamespace = "https://ssl.selectpayment.com/PV")
        ArrayOfInt locationIds,
        @WebParam(name = "returnedBeginDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar returnedBeginDate,
        @WebParam(name = "returnedEndDate", targetNamespace = "https://ssl.selectpayment.com/PV")
        XMLGregorianCalendar returnedEndDate);

    /**
     * 
     * @param storeKey
     * @param entityId
     * @param storeId
     * @param collectionId
     * @return
     *     returns WSCollectionDetail
     */
    @WebMethod(operationName = "GetCollectionDetails", action = "https://ssl.selectpayment.com/PV/GetCollectionDetails")
    @WebResult(name = "GetCollectionDetailsResult", targetNamespace = "https://ssl.selectpayment.com/PV")
    @RequestWrapper(localName = "GetCollectionDetails", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetCollectionDetails")
    @ResponseWrapper(localName = "GetCollectionDetailsResponse", targetNamespace = "https://ssl.selectpayment.com/PV", className = "GetCollectionDetailsResponse")
    public WSCollectionDetail getCollectionDetails(
        @WebParam(name = "storeId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long storeId,
        @WebParam(name = "storeKey", targetNamespace = "https://ssl.selectpayment.com/PV")
        String storeKey,
        @WebParam(name = "entityId", targetNamespace = "https://ssl.selectpayment.com/PV")
        int entityId,
        @WebParam(name = "collectionId", targetNamespace = "https://ssl.selectpayment.com/PV")
        long collectionId);

}
